ci: Prevent darwin and musl targets from using rustc-llvm-proxy
`rustc-llvm-proxy` used to work on musl targets by accident because
`LD_LIBRARY_PATH` let it `dlopen` our shared LLVM library.

After switching to `rpath`, that no longer works: our shared LLVM
library is not visible to `rustc-llvm-proxy`, and musl Rust toolchains
ship `libLLVM` statically, so there is no shared library for
`rustc-llvm-proxy` to load. This caused CI failures such as:

  unable to read dir /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib: No such file or directory (os error 2)
  thread 'test_link_ir_files' (4) panicked at /rustc/cf7da0b7277cad05b79f91b60c290aa08a17a6f0/library/core/src/panicking.rs:225:5:
  [...]
  unable to read dir /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib: No such file or directory (os error 2)
  unable to read dir /root/.cargo/lib: No such file or directory (os error 2)
  thread 'test_link_ir_files' (4) panicked at /home/runner/work/bpf-linker/bpf-linker/bpf-linker/target/x86_64-unknown-linux-musl/debug/build/aya-rustc-llvm-proxy-5f163ea45ef44b54/out/llvm_gen.rs:14919:10:
  LLVMParseIRInContext2: DlSym { source: "Symbol not found: LLVMParseIRInContext2" }

The behavior on darwin targets is not reliable. Stable Rust toolchains
for macOS link `libLLVM` statically. Nightly tried to switch to dynamic
linking[0][1], but those attempts were reverted twice[2][3].

Prevent any related issues by excluding `default` and `rust-llvm-*`
features on darwin and musl targets.