xtask: Add `musl-sysroot-url` subcommand
Add a submcommand that prints the full URL of a musl sysroot tarball
from Gentoo[0][1] for the given architecture.

These tarballs are convenient to use for building bpf-linker for the
`*-unknown-linux-musl` targets in GitHub actions. They contain static
libstdc++ that's linked to musl.

We need to link libstdc++ becuase libLLVM provided by Rust CI are
linked dynamically to it. Producing a static binary requires a static
libstdc++ to provide missing symbols.

Building bpf-linker for `*-unknown-linux-musl` targets using Ubuntu's
libstdc++ does not work because it's linked dynamically to glibc,
causing linking errors like:

```
(.text._ZNSt6locale13_S_initializeEv+0x0): undefined reference to `__libc_single_threaded'
```

Using Gentoo's tarball and referencing it in `CXXSTDLIB` variable
solves the problem. After unpacking the tarball to `sysroot/`, one can
build a static binary using the following command on any distro:

```
RUSTFLAGS="-C target-feature=+crt-static" \
    CXXSTDLIB_PATH="$(dirname $(find sysroot/ -name libstdc++.a))" \
    cargo +nightly test \
    --features llvm-21,llvm-link-static --no-default-features \
    --target x86_64-unknown-linux-musl
```

Why Gentoo? It's more convenient than the considered alternatives:

- Alpine Linux minirootfs[2] does not contain libstdc++. Neither does
  Void Linux rootfs[3]. One would need to chroot into it the sysroot and
  install it, which requires more work.
- musl.cc[4] did not provide any update update since 2021.
- Chimera Linux[5] uses LLVM libc++.

[0] https://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-musl/
[1] https://distfiles.gentoo.org/releases/arm64/autobuilds/current-stage3-arm64-musl/
[2] https://www.alpinelinux.org/downloads/
[3] https://voidlinux.org/download/#download-installable-base-live-images-and-rootfs-tarballs
[4] https://musl.cc/
[5] https://chimera-linux.org/