chore: Update rustc-build-sysroot to 0.5.13
It should fix the following error occuring during the BPF sysroot build:

  thread 'compile_test' (5840) panicked at tests/tests.rs:145:14:
  failed to build sysroot: sysroot build failed; stderr:
  error: failed to select a version for `compiler_builtins`.
      ... required by package `custom-local-sysroot v0.0.0 (/tmp/.tmp2ivnrS)`
  versions that meet the requirements `*` (locked to 0.1.160) are: 0.1.160