Install llvm-18 instead of llvm-18-dev
It's not clear why we need -dev and this is currently failing in CI:
```
The following packages have unmet dependencies:
 libllvm18 : Breaks: llvm-18-dev (< 1:18.1.8~++20240730104741) but
1:18.1.8~++20240730092223+3b5b5c1ec4a3-1~exp1~20240730092238.143 is to
  be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```